// react-demo/src/launcher.tsx
import { useRef, useEffect } from 'react'
import { Launcher } from 'live-dragon'
import { Options } from './interface'

interface Props {
  url: string
  iceConfig: RTCIceServer[]
  options?: Partial<Options>
}

/**
 * Creating application from PaaS. No matter mobile or PC application.
 */
function LDLauncher(props: Props) {
  const { url, iceConfig, options } = props
  const launcher = useRef<Launcher>()
  const containerRef = useRef<HTMLDivElement>(null!)

  useEffect(() => {
    launcher.current = new Launcher(
      url,
      iceConfig,
      containerRef.current,
      options
    )
    return () => {
      /**
       * SDK Warning: WebSocket is closed before the connectin is established
       * because of the Strict mode in development mode of react18. In React18,
       * you can remove Strict mode to test it.
       */
      launcher.current?.destory()
    }
  }, [])

  return (
    <div
      ref={containerRef}
      style={{ width: '100%', height: '100%', position: 'relative' }}
    ></div>
  )
}

export default LDLauncher

// svelte-demo/src/launcher.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { Launcher } from 'live-dragon'
  import type { Options } from './interface'

  export let url: string
  export let iceConfig: RTCIceServer[]
  export let options: Partial<Options> | undefined = undefined

  let wrap: HTMLDivElement
  let launcher: Launcher | null = null

  onMount(() => {
    launcher = new Launcher(url, iceConfig, wrap, options)
  })

  onDestroy(() => {
    launcher?.destory()
    launcher = null
  })

</script>

<div class="wrap" bind:this={wrap} />

<style>
  .wrap {
    width: 100%;
    height: 100%;
  }
</style>
