// svelte-demo/src/App.svelte
<script lang="ts">
  import Launcher from './launcher.svelte'

  const url = 'replace_signaling_url_here'
  const iceConfig = [
    {
      urls: 'replace_coturn_url_here',
      username: 'replace_coturn_username_here',
      credential: 'replace_coturn_password_here',
    },
  ]
</script>

<main class="container">
  <Launcher {url} {iceConfig} />
</main>

<style>
  .container {
    width: 100%;
    height: 100vh;
  }
</style>

// react-demo/src/App.tsx
import Launcher from './launcher'

function App() {
  const url = 'replace_signaling_url_here'
  const iceConfig = [
    {
      urls: 'replace_coturn_url_here',
      username: 'replace_coturn_username_here',
      credential: 'replace_coturn_password_here',
    },
  ]

  return (
    <div style={{ width: '100%', height: '100vh' }}>
      <Launcher url={url} iceConfig={iceConfig} />
    </div>
  )
}

export default App
