// svelte-demo/src/mobile-launcher.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { MobileLauncher } from 'live-dragon'
  import type { Options } from './interface'

  export let url: string
  export let iceConfig: RTCIceServer[]
  export let options:
    | Partial<Options & { enableNavigation: boolean }>
    | undefined = undefined

  let wrap: HTMLDivElement
  let launcher: MobileLauncher | null = null

  onMount(() => {
    launcher = new MobileLauncher(url, iceConfig, wrap, options)
  })

  onDestroy(() => {
    launcher?.destory()
    launcher = null
  })
</script>

<div class="wrap" bind:this={wrap} />

<style>
  .wrap {
    width: 100%;
    height: 100%;
  }
</style>

// react-demo/src/mobile-launcher.tsx
import { useRef, useEffect } from 'react'
import { MobileLauncher } from 'live-dragon'
import { Options } from './interface'

interface Props {
  url: string
  iceConfig: RTCIceServer[]
  options?: Partial<
    Options & {
      enableNavigation: boolean
    }
  >
}

function MBLauncher(props: Props) {
  const { url, iceConfig, options } = props

  const hostRef = useRef<HTMLDivElement>(null!)
  const mobileLauncher = useRef<MobileLauncher>()

  useEffect(() => {
    mobileLauncher.current = new MobileLauncher(
      url,
      iceConfig,
      hostRef.current,
      options
    )

    return () => {
      /**
       * SDK Warning: WebSocket is closed before the connectin is established
       * because of the Strict mode in development mode of react18. In React18,
       * you can remove Strict mode to test it.
       */
      mobileLauncher.current?.destory()
    }
  }, [])

  return (
    <div
      ref={hostRef}
      style={{ width: '100%', height: '100%', position: 'relative' }}
    ></div>
  )
}

export default MBLauncher
